# Generated by Django 4.0.4 on 2022-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_cadastro',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
