# Generated by Django 4.0.4 on 2022-05-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sobrenome',
        ),
    ]
