# Generated by Django 4.0.4 on 2022-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_email_remove_profile_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Contato',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
