# Generated by Django 4.0.4 on 2022-05-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_contato_profile_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Contato',
            new_name='contato',
        ),
        migrations.AlterField(
            model_name='profile',
            name='data_cadastro',
            field=models.DateField(auto_created=True, auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='users/'),
        ),
    ]
