# Generated by Django 4.0.4 on 2022-05-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pontos_turisticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('funcionamento', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Aberto'), ('B', 'Fechado'), ('R', 'Reforma')], max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('I', 'Adolescente'), ('A', 'Adulto'), ('V', 'Idoso')], max_length=30, null=True)),
            ],
        ),
    ]
