# Generated by Django 4.0.4 on 2022-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='favorito',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
