# Generated by Django 4.0.4 on 2022-05-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_pontos_turisticos_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
