# Generated by Django 4.0.4 on 2022-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_pontos_turisticos_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagem_slider_ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens', models.ImageField(blank=True, null=True, upload_to='pontos-turisticos/')),
            ],
        ),
        migrations.AddField(
            model_name='pontos_turisticos',
            name='img',
            field=models.ManyToManyField(blank=True, null=True, to='plataforma.imagem_slider_ponto'),
        ),
    ]
