# Generated by Django 4.0.4 on 2022-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_imagem_slider_ponto_pontos_turisticos_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='img_capa',
            field=models.ImageField(blank=True, null=True, upload_to='pontos-turisticos/capa'),
        ),
    ]
