# Generated by Django 4.0.4 on 2022-05-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_pontos_turisticos_img_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('I', 'Infantil'), ('A', 'Adulto'), ('V', 'Idoso')], max_length=30, null=True),
        ),
    ]
